apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: supplychain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/ibrahimelothmani/inventory-backend:29589a16d1b55d6c7b3cb0e48bfd3e87ce21aa91
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres.supplychain.svc.cluster.local:5432/inventory_db
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
