apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: supplychain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/${{ github.repository_owner }}/inventory-frontend:latest
        ports:
        - containerPort: 80
