apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: supplychain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/ibrahimelothmani/inventory-frontend:29589a16d1b55d6c7b3cb0e48bfd3e87ce21aa91
        ports:
        - containerPort: 80
