apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supplychain-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ibrahimelothmani/Supply-Chain.git'
    path: charts/supplychain
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: supplychain
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
