namespace: supplychain
replicaCount:
  backend: 2
  frontend: 2
image:
  repository: ghcr.io/ibrahimelothmani
  backendTag: 07dc59997037e60148e41ccbf34022bc73e492e2
  frontendTag: 07dc59997037e60148e41ccbf34022bc73e492e2
vault:
  enabled: false
  secretPath: secret/data/supplychain/backend
ingress:
  host: supplychain.local
database:
  dbName: inventory_db
  username: postgres
  # Insecure default, meant to be overridden by Vault later
  password: postgres
